### ISSUE TITLE
这个错误怎么办

### ISSUE THREAD

**Issue by ghost** [ShadowsocksR-Live/ssrMac#11]
<img width="768" alt="截屏2020-03-11下午5 28 10" src="https://user-images.githubusercontent.com/18343966/76402538-85ec1880-63be-11ea-974b-51ec86d3884f.png">

**Comment by aishuidedabai** [comment]
<img width="768" alt="截屏2020-03-11下午5 28 10" src="https://user-images.githubusercontent.com/18343966/76402380-550be380-63be-11ea-921e-9c68c67c5760.png">
