### ISSUE TITLE
如何发布app

### ISSUE THREAD

**Issue by niancan** [ShadowsocksR-Live/ssrMac#13]
我想知道 作者,你是如何无需签名 制作的app
我通过archive包,别人是无法运行的

**Comment by ssrlive** [comment]
估计新版macOS不行了，新系统禁止任何未签名的软件运行了。未签名包只能在 10.14以下系统运行。

**Comment by niancan** [comment]
遗憾, 因为catalina无法制作app, 所以我正在写mac版networkexten,基本上功能是写完了,但是远程dns查询 没有返回,不知道这个我们可以交流一下吗？如果完成,我可以开源 networkextens部分。

**Comment by ssrlive** [comment]
SSRoT 已经支持标准SOCKS5协议的 UDP 转发，这得借助 tun2socks 软件的帮忙，把 tun2socks 集成进来就可以形成一个完整的 extension 数据包转发链条了。

**Comment by ssrlive** [comment]
dns 查询实际上是 udp 53 端口。

**Comment by niancan** [comment]
SSRoT 我将他改为 OSX 编译, 出现了一些问题, 我开启https代理 那么 在国外 就无法正常访问http,如果我关闭https只开启http,那么国内无法访问https内容.如果都开启,国外和内陆 都会无法访问web内容。

**Comment by ssrlive** [comment]
如果dns不走代理就有可能被GFW投毒污染。

**Comment by niancan** [comment]
以下是outline的dns远程查询,这部分数据  ssr for pyton是可以收到数据,处理并返回,但是 我无法收到这个返回。现在卡在这里
`    uint16_t dnsRequestId = [self getDnsRequestId:metadata.data];
    [self.localAddrByDnsReqId setObject:[self encodeIpAddress:&metadata.srcAddress]
                                 forKey:[NSString stringWithFormat:@"%d", dnsRequestId]];

    struct socks_udp_header socksHeader = { .rsv = 0, .frag = 0, .atyp = SOCKS_ATYP_IPV4 };
    struct socks_addr_ipv4 address = { .addr = metadata.ipHeader->dest.addr,
                                       .port = metadata.udpHeader->dest };
    size_t packetNumBytes = SOCKS_HEADER_NUM_BYTES + SOCKS_ADDRESS_NUM_BYTES + metadata.dataNumBytes;
    uint8_t socksPacket[packetNumBytes];
    memset(socksPacket, 0, packetNumBytes);
    
    memcpy(socksPacket, &socksHeader, SOCKS_HEADER_NUM_BYTES);
    memcpy(socksPacket + SOCKS_HEADER_NUM_BYTES, &address, SOCKS_ADDRESS_NUM_BYTES);
    memcpy(socksPacket + SOCKS_HEADER_NUM_BYTES + SOCKS_ADDRESS_NUM_BYTES,metadata.data, metadata.dataNumBytes);
    
    NSData* packetData = [[NSData alloc] initWithBytes:socksPacket length:packetNumBytes];
    [self.udpSocket sendData:packetData toHost:LOCALHOST_IP port:self.socksServerPort
                 withTimeout:UDP_TIMEOUT_SECS
                         tag:dnsRequestId];`

ssr for python日志:
`
2020-09-03 15:20:57 DEBUG    udprelay.py:623 DNS query 216.146.35.35 from ::ffff:106.114.233.242:5668
2020-09-03 15:20:57 DEBUG    udprelay.py:632 UDP port 60000 sockets 5
2020-09-03 15:20:57 DEBUG    udprelay.py:679 UDP data to 216.146.35.35:53 from ::ffff:106.114.233.242:5668 via port 60000
2020-09-03 15:20:57 DEBUG    udprelay.py:729 UDP data to 216.146.35.35(216.146.35.35):53 from 0.0.0.0:30774 by user 60000
2020-09-03 15:20:57 DEBUG    udprelay.py:809 remove dns client ::ffff:106.114.233.242:5668
2020-09-03 15:20:57 DEBUG    udprelay.py:309 close_client: (('::ffff:106.114.233.242', 5668, 0, 0), <AddressFamily.AF_INET: 2>)
`

**Comment by niancan** [comment]
以下是outline的dns远程查询,这部分数据  ssr for pyton是可以收到数据,处理并返回,但是 我无法收到这个返回。现在卡在这里
`c 
    uint16_t dnsRequestId = [self getDnsRequestId:metadata.data];
    [self.localAddrByDnsReqId setObject:[self encodeIpAddress:&metadata.srcAddress]
                                 forKey:[NSString stringWithFormat:@"%d", dnsRequestId]];

    struct socks_udp_header socksHeader = { .rsv = 0, .frag = 0, .atyp = SOCKS_ATYP_IPV4 };
    struct socks_addr_ipv4 address = { .addr = metadata.ipHeader->dest.addr,
                                       .port = metadata.udpHeader->dest };
    size_t packetNumBytes = SOCKS_HEADER_NUM_BYTES + SOCKS_ADDRESS_NUM_BYTES + metadata.dataNumBytes;
    uint8_t socksPacket[packetNumBytes];
    memset(socksPacket, 0, packetNumBytes);
    
    memcpy(socksPacket, &socksHeader, SOCKS_HEADER_NUM_BYTES);
    memcpy(socksPacket + SOCKS_HEADER_NUM_BYTES, &address, SOCKS_ADDRESS_NUM_BYTES);
    memcpy(socksPacket + SOCKS_HEADER_NUM_BYTES + SOCKS_ADDRESS_NUM_BYTES,metadata.data, metadata.dataNumBytes);
    
    NSData* packetData = [[NSData alloc] initWithBytes:socksPacket length:packetNumBytes];
    [self.udpSocket sendData:packetData toHost:LOCALHOST_IP port:self.socksServerPort
                 withTimeout:UDP_TIMEOUT_SECS
                         tag:dnsRequestId];
`

ssr for python日志:

`c
2020-09-03 15:20:57 DEBUG    udprelay.py:623 DNS query 216.146.35.35 from ::ffff:xx.xx.xx.xx:5668

2020-09-03 15:20:57 DEBUG    udprelay.py:632 UDP port 60000 sockets 5

2020-09-03 15:20:57 DEBUG    udprelay.py:679 UDP data to 216.146.35.35:53 from ::ffff:xx.xx.xx.xx:5668 via port 60000

2020-09-03 15:20:57 DEBUG    udprelay.py:729 UDP data to 216.146.35.35(216.146.35.35):53 from 0.0.0.0:30774 by user 60000

2020-09-03 15:20:57 DEBUG    udprelay.py:809 remove dns client ::ffff:xx.xx.xx.xx:5668

2020-09-03 15:20:57 DEBUG    udprelay.py:309 close_client: (('::ffff:xx.xx.xx.xx', 5668, 0, 0), <AddressFamily.AF_INET: 2>)

`

**Comment by ssrlive** [comment]
我对于 SSR 的原始实现进行的 UDP relay 客户端进行了删改，可能无法代理 SSR python 服务器的UDP 流量。

**Comment by ssrlive** [comment]
你有运行python 客户端代理 UDP 流量吗？

**Comment by niancan** [comment]
你需要的是代码 还是日志？

**Comment by ssrlive** [comment]
你现在的服务端配置是什么？是python版还是 native版 还是 SSRoT？

**Comment by niancan** [comment]
python版

**Comment by ssrlive** [comment]
客户端的代码是哪个？python版还是 native 版？

**Comment by niancan** [comment]
客户端使用的是 shadowsocksr-uvw  版本 ,我想这部分应该是没有问题的。
因为域名查询,是单独起一个socket 封装了一个dns查询,此部分并没有进入shadowsocksr
# SOCKS5 UDP Request
# +----+------+------+----------+----------+----------+
# |RSV | FRAG | ATYP | DST.ADDR | DST.PORT |   DATA   |
# +----+------+------+----------+----------+----------+
# | 2  |  1   |  1   | Variable |    2     | Variable |
# +----+------+------+----------+----------+----------+

现在的是问题,请求可以发过去,python也可以处理这个请求,但是python将结果返回,我这边socket无法收到结果

**Comment by ssrlive** [comment]
你把python打算返回给客户端的数据包拦截下来，里边是什么？目标地址是什么？

**Comment by ssrlive** [comment]
我怀疑是python服务端有问题。

**Comment by niancan** [comment]
python返回的信息 除了端口与我本地发送的端口不一致,其他信息是没有问题的。
但是我用sstap去检测,他返回的端口与本地发送的端口也是不一致,所以 我有点搞不懂了
`
udprelay.py:623 DNS query 216.146.35.35 from ::ffff:MyIP:5668         

udprelay.py:632 UDP port 60000 sockets 5                   
                      
udprelay.py:679 UDP data to 216.146.35.35:53 from ::ffff:MyIP:5668 via port 60000   

udprelay.py:729 UDP data to 216.146.35.35(216.146.35.35):53 from 0.0.0.0:30774 by user 60000

udprelay.py:809 remove dns client ::ffff:MyIP:5668

udprelay.py:309 close_client: (('::ffff:MyIP', 5668, 0, 0), <AddressFamily.AF_INET: 2>)
`
日志比较短,从日志内容,可以观测到执行过程, 在remove dns client.... 之前 会把数据 sento到 Myip

**Comment by ssrlive** [comment]
你看到 sendto myIP 了吗？从日志看去，似乎是发送到远程后就关了udp socket，根本没等到远端返回。

**Comment by niancan** [comment]
![WX20200904-001228](https://user-images.githubusercontent.com/6178530/92140256-7288aa00-ee43-11ea-99b4-78347d2530b0.png)

这是python源码.按道理说执行了sendto 无论结果是什么,我这边的socket应该会收到结果,可是我这边的socket无法收到他的返回

**Comment by ssrlive** [comment]
客户端在发送数据包时，会将数据包用SSR加密算法加密，然后再封装成S5风格的一个数据包发送给服务端。 

服务端收到客户端的udp数据包后，将有效荷载数据再解密出来。 否则数据包就是错的，DNS服务器会直接丢弃错误的DNS查询数据包的。

你客户端封包时似乎没做加密。

**Comment by niancan** [comment]
我想应该不是客户端未加密数据的问题,如果是这个问题 python在解析data数据的时候 应该就会报 decrypt data failed 
现在的问题是,我数据发送给python服务端, python服务端也正常处理并返回了,可是我无法接收到这个返回

以下图片是 客户端 封装dns查询请求
![1](https://user-images.githubusercontent.com/6178530/92142642-bdf08780-ee46-11ea-83d2-c707895528a8.png)

以下图片是对mac Utun packet数据的解析
![2](https://user-images.githubusercontent.com/6178530/92142674-c9dc4980-ee46-11ea-8510-7f7a42c8b0ac.png)

**Comment by ssrlive** [comment]
metadata.data = data; 中，data 在赋值之前，得SSR加密。

**Comment by ssrlive** [comment]
https://github.com/Qv2ray/shadowsocksr-uvw/blob/699c1b2d17bbac90357d630f7097c3dce1c19c7d/src/UDPRelay.cpp#L203

**Comment by niancan** [comment]
ok,我应该在shadowsocksr-uvw ->UDPRelay.cpp->Recv 加入日志 以观测数据是否回到ssr. 
非常感谢，我这边如果完成会给你发送一个network extension的源码.目前来说应该是ssr中的udprepay，接收结果可能报错了 导致我dns查询无法收到结果

**Comment by ssrlive** [comment]
ok

**Comment by ssrlive** [comment]
BTW 我恨透了苹果。

**Comment by niancan** [comment]
我想我和你一样,恨透苹果 

现在ssr报错,ipv6设置.查了近2天资料,无解
![image](https://user-images.githubusercontent.com/6178530/92309045-90d1df80-efd4-11ea-908f-79e8155ab197.png)

以下code
      rc = setsockopt(fd, IPPROTO_IPV6, IPV6_TCLASS, &tos, sizeof(tos));
        if (rc < 0 && errno != ENOPROTOOPT) {                
            LOGE("setting ipv6 dscp failed: %d", errno);          
        }  

errno = 22 （参数无效,我猜可能mac没有`IPV6_TCLASS`设置选项）

关于 IPV6_TCLASS 设置,不知你有没有答案？
