### ISSUE TITLE
Do not support certain protocol_param

### ISSUE THREAD

**Issue by Ccii77** [ShadowsocksR-Live/ssrMac#15]
几个BUG，我没法做更深的analysis，I am not a coder. Using Macos Yosemite 10.10.5

1.我购买了SSR地址，把decode的地址填入后，无法上网。我把地址放在android上的SSR https://github.com/shadowsocksrr/shadowsocksr-android/releases/tag/3.5.4  是可以使用的，证明我地址没问题。 我用了其他的SSR地址，你的程序是可以使用的，证明安装也没问题。我购买的地址与其他地址的区别 Encryption chacha20 protocol auth_aes128_sha1 protocal_param 里面是  9999999     :9a9a9a9a9a9a9a9a  这种模式。我的address有21个字节比较长，并且全英文。我估计应该是protocal_param的问题。

2.要运行程序联网成功，需要先双击图标进入程序，选好服务器，选好代理，选择on后直接quit。然后再次双击图标再次启动。 
正常来说进入程序时，是off状态，选好服务器和代理模式后 选择on就可以上网。我这里不行。应该是个小bug。

3.我第一次运行时，遇到 Segmentation Fault 11    Abort Trap 6，我就重启了cfprefsd，后面就没遇到这样的问题了。但是如果我完全重新安装，这问题还会再出现。

希望你下个更新的版本可以解决这些bug，并且将来会加入订阅链接的module，目前10.10的mac想用SSR的GUI，真没找到什么其他选项，希望继续加油。

**Comment by Ccii77** [comment]
折腾了两天。。。有点收获。第一你这个ssrMAC基本上是最后一个10.10能装的ssr GUI了，我是把github上面有的都试了。你的虽然没有订阅但是至少能用，本来的功能没有啥缺陷。以下是我对之前发现的bug更新。

1.我分析了代码，才明白，原来是空格的问题。protocal_param的“通用格式”是9999999五个空格:9a9a9a9a9a9a9a9a;你的不能有空格。
2.启动问题照旧，关闭前在on的状态并且选好代理模式，退出程序再进入程序。
3.这个bug再也没出现过，您可以增加个verbose log，比较好查原因。

希望您下次发布时，单独发布个10.10版，用10.10的sdk，既然你都要用到10.9的一些东西，你肯定也有10.10的sdk吧，🙏🙏🙏
我完全不懂代码，上面只是分析的结果，我本想尝试自己build，不过下好的有些代码在xcode里面报错，我就没法改了。

**Comment by Ccii77** [comment]
我的protocol 是 auth_aes128_sha1  protocol_param 格式为 9999999:9a9a9a9a9a9a9a9a； 其实不就是个服务器端的用户名和密码。只不过我是买的，没法修改，您帮帮忙看一下吧。问题应该就是这个。

**Comment by ssrlive** [comment]
https://github.com/ShadowsocksR-Live/shadowsocksr-native/blob/master/src/ssr_executive.c#L140
这是服务端对 protocol_param 参数的处理。如果你真的对这个很关心，你就跟踪进去这段代码，而不是仅仅纠缠于mac 客户端。

**Comment by Ccii77** [comment]
感谢你的回复。我没法上得到服务器。。。我只是个付费用户。
我知道服务器上大概是这种形式 /* "protocol_param":"64#12345:breakwa11,233:breakwa11", */
用户端就是 "protocol_param":"1234:breakwa11"     问题是我用这个配置在android手机版SSR用户端,可以连接成功。你的mac版用户端我也试过连接其他的protocol_param配置的服务器也能成功。那就只能是你mac用户端里面对我这个特殊的protocol_param配置不支持了，我一下把我的具体连接信息发邮件给你吧，你试试。
我看不太懂代码，只能靠英文以及逻辑去理解，大神你见谅。

**Comment by ssrlive** [comment]
由于 SSRoT 已经去掉了 协议和混淆，再维护这段代码失去了意义，后向兼容的原始 SSR 根本没有前途。参见 [Wiki](https://github.com/ShadowsocksR-Live/shadowsocksr-native/wiki) 。

为了你的信息安全，最好你自己购买 VPS 自己安装服务器。这些目前在兲朝还可以做，以后国门关死，大家都当猪去吧。

**Comment by ssrlive** [comment]
如果你手头不宽裕，Wiki 也介绍了几种免费获得服务端资源的方法，不用花钱。自己找。

PS. 测试自己的完毕，没问题。测试你的，没通过。没工夫猜他们的服务器实现了。结案。

![image](https://user-images.githubusercontent.com/30760636/99736032-a6997000-2b00-11eb-9e5a-3879e0226954.png)

**Comment by Ccii77** [comment]
大神，骚扰邮件已发。行不行你说了算。不管怎样，谢谢你的回复。

**Comment by ssrlive** [comment]
用 [python 版](https://github.com/ShadowsocksR-Live/shadowsocksr) 原始服务端测试，ssr-Native 没有问题，你找机场主理论去。

![image](https://user-images.githubusercontent.com/30760636/99855180-2c7cf000-2bc1-11eb-96c4-000632744d07.png)
