### ISSUE TITLE
自定义本地端口

### ISSUE THREAD

**Issue by FreeHoneyPie** [ShadowsocksR-Live/ssrMac#19]
作者你好，
我在使用Mac客户端时发现本地的端口是被默认设为1080，在1080端口占用时会依次尝试1081和之后的端口。我想能不能像shadowsocks客户端一样，加一个自定义本地端口的功能？或者至少在启动后加一条应用在监听哪个本地端口的提示？
我现在只能通过lsof -i:1080 这样去看客户端到底在哪个端口上。

**Comment by ssrlive** [comment]
主意是好，但我目前没时间修改，你能援手吗？

**Comment by ssrlive** [comment]
监听端口已经显示在主菜单上。
