### ISSUE TITLE
ssrMac/shadowsocksr-native/depends/uv-mbed/ directory is missing

### ISSUE THREAD

**Issue by zonzi** [ShadowsocksR-Live/ssrMac#8]
the uv-mbed directory is missing in current ssrMac. The issue is the specific version of shadowsocksr-native. The folder seems set properly in the newest master version.

**Comment by ssrlive** [comment]
please keep `git submodule update --init`, do `NOT` up to date.

**Comment by zonzi** [comment]
hi, this one works. Thank you very much!


the proper procedure seems the below:

$git clone https://github.com/ShadowsocksR-Live/ssrMac.git
$cd ssrMac
$git submodule update --init --recursive
$git submodule foreach -q 'git checkout $(git config -f $toplevel/.gitmodules submodule.$name.branch || echo master)'
$git submodule update --init

run xcode and set a team for ssrMac and ssr_mac_config.

**Comment by ssrlive** [comment]
Yes I forget to remove the line.
It’s always work.
