### ISSUE TITLE
ssrMac can't be opened on macOS Catalina Beta

### ISSUE THREAD

**Issue by jpalidev** [ShadowsocksR-Live/ssrMac#9]
Testing on macOS Catalina Beta in a virtual machine produces a message: "ssrMac can't be opened because Apple cannot check it for malicious software. This software needs to be updated. Contact the developer for more information."

![catalina-ssrmac](https://user-images.githubusercontent.com/52431237/63608263-63f98880-c589-11e9-85e1-505a4ae42059.png)

**Comment by ssrlive** [comment]
Maybe it can work.

```
sudo spctl --master-disable

```

![Screen Shot 2019-08-24 at 12 42 02 AM](https://user-images.githubusercontent.com/30760636/63608790-6818bb00-c608-11e9-9227-cfb04d9732a1.png)

**Comment by jpalidev** [comment]
It defaults to allow apps downloaded from App Store and identified developer:

![catalina-ssrmac-2](https://user-images.githubusercontent.com/52431237/63629072-d8055200-c5c4-11e9-87df-bd087809ded2.png)

Is this note on the Apple Developer site relevant?

"Mac apps, installer packages, and kernel extensions that are signed with Developer ID must also be notarized by Apple in order to run on macOS Catalina."

https://developer.apple.com/news/?id=06032019i

**Comment by ssrlive** [comment]
maybe [this video](https://www.youtube.com/watch?v=AnCyEeOt82I) can help.

I don't want the CCP cops arrest me, so I can NOT leak any personal info.

**Comment by jpalidev** [comment]
Thanks.
